version: '3.8'
services:
  immatriculation-service:
    build:
      context: ./immatriculation-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - mynetwork

  infraction-service:
    build:
      context: ./infraction-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    networks:
      - mynetwork

  radar-service:
    build:
      context: ./radar-service
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    networks:
      - mynetwork

  frontend:
    build:
      context: ./radar-web-app
      dockerfile: Dockerfile

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    networks:
      - mynetwork

  eureka-discovery:
    build:
      context: ./eureka-discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - mynetwork

networks:
  mynetwork:
